name: nf-core-hic-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=2.7.11
  - conda-forge::scipy=0.18.1
  - conda-forge::numpy=1.12.1
  - bcbio::bx-python=0.5.0
  - bioconda::pysam=0.8.3
  - cooler=0.8.3
  - bowtie2=2.2.9
  - samtools=1.9
  - multiqc=1.6
